### ISSUE TITLE
Better documentation/discussion for error handling

### ISSUE THREAD

**Issue by prabirshrestha** [trillium-rs/trillium#23]
Would it be possible to add error handling example in https://trillium.rs/ ?

Doc are great by the way for a new project.

**Comment by jbr** [comment]
> Doc are great by the way for a new project.
Thanks!

The absence of error handling is not entirely a mistake, but I should address it directly in the documentation. Currently, the error handling story is the least-developed aspect of Trillium, but we are limited by what the language can express at the moment. In the future, we'll be able to have a `ErrorHandler::new(async move |conn: &Conn| → Result<(), MyResult> { Ok(()) })` that impl's Handler, but until the language develops that capability, it's a matter of picking the least-bad workaround.

There are two macros available to make this easier: [trillium::conn_try!](https://docs.trillium.rs/trillium/macro.conn_try.html) and [trillium::conn_unwrap!](https://docs.trillium.rs/trillium/macro.conn_unwrap.html), but I expect there'll be further improvements.

Regardless of how it turns out, error handling is going to end up looking very different from tide. In particular, I think there's a distinction between "returning a non-200 response" and a rust Err, and that the code to translate between them should live entirely in the application. I think most applications will want to have a single thiserror-style enum Error that also implements Handler.

**Comment by prabirshrestha** [comment]
I was actually looking into some sort of error handling sort of middleware (handler) that auto converts errors to json/html bad requests or 500 or `thiserror` to some json represntation.

```rust
trillium_smol::run(
    Router::new()
        .get("/users", {conn-> Err('blah') ))
        .get("/posts", posts_api),
    ErrorHandler::new(async move |conn: &Conn| -> {
        conn.with_status(500).with_body(json!(conn.err()))
    });
);
```

**Comment by jbr** [comment]
Yeah, that's not possible yet in async rust

**Comment by jbr** [comment]
I'm going to convert this to a discussion because I believe this will be a long-running topic of discussion, but will re-create an issue to represent the short term need for better documentation
