### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by lucperkins** [trillium-rs/trillium#56]
It'd be nice to have a Trillium plugin for turning an endpoint into a GraphQL interface. To my knowledge there are really only two major GraphQL implementations for Rust, Juniper and `async-graphql`, and plug-ins could potentially be provided for both.

**Comment by jbr** [comment]
Was *just* chatting with @MilanLoveless about how easy it'd be to make a juniper handler. I'm not sure if _I_ should make that crate though (trying to focus on these https://github.com/trillium-rs/trillium/discussions/41), but I'd be happy to assist

Switching this to a discussion because it's not an improvement to one of the existing crate, but a proposed new crate for someone to build
